/**
 * Tibia Delivery Task — Item & Task Data
 *
 * Each task entry describes one NPC delivery:
 *  - id          : unique key
 *  - npc         : NPC name
 *  - location    : city / area
 *  - taskName    : display name for the task
 *  - items       : array of { name, quantity, npcPrice }
 *                   npcPrice = gold the NPC pays per item
 *  - rewardGold  : extra flat gold bonus on top of item prices (0 if none)
 *  - rewardXP    : experience reward (0 if none)
 *  - rewardItems : array of { name, marketValue } — bonus items rewarded
 *  - notes       : optional hint string
 */

const TASKS = [
  /* ─────────────────────────────── RASHID ─────────────────────────────── */
  {
    id: "rashid_monday",
    npc: "Rashid",
    location: "Svargrond (Monday)",
    taskName: "Rashid's Daily Buy — Monday",
    items: [
      { name: "Mammoth Fur Cape",       quantity: 1, npcPrice: 2000  },
      { name: "Mammoth Fur Shorts",      quantity: 1, npcPrice: 2000  },
      { name: "Mammoth Whopper",         quantity: 1, npcPrice: 2000  },
      { name: "Norseman Doll",           quantity: 1, npcPrice: 200   },
    ],
    rewardGold: 0,
    rewardXP: 0,
    rewardItems: [],
    notes: "Rashid buys different items each day based on his location.",
  },
  {
    id: "rashid_tuesday",
    npc: "Rashid",
    location: "Carlin (Tuesday)",
    taskName: "Rashid's Daily Buy — Tuesday",
    items: [
      { name: "Cyclops Trophy",          quantity: 1, npcPrice: 1000  },
      { name: "Minotaur Trophy",         quantity: 1, npcPrice: 1000  },
      { name: "Troll Trophy",            quantity: 1, npcPrice: 200   },
      { name: "Orc Trophy",              quantity: 1, npcPrice: 500   },
    ],
    rewardGold: 0,
    rewardXP: 0,
    rewardItems: [],
    notes: "",
  },
  {
    id: "rashid_wednesday",
    npc: "Rashid",
    location: "Thais (Wednesday)",
    taskName: "Rashid's Daily Buy — Wednesday",
    items: [
      { name: "Ancient Shield",          quantity: 1, npcPrice: 3000  },
      { name: "Viking Helmet",           quantity: 1, npcPrice: 1000  },
      { name: "Battle Shield",           quantity: 1, npcPrice: 400   },
    ],
    rewardGold: 0,
    rewardXP: 0,
    rewardItems: [],
    notes: "",
  },
  {
    id: "rashid_thursday",
    npc: "Rashid",
    location: "Kazordoon (Thursday)",
    taskName: "Rashid's Daily Buy — Thursday",
    items: [
      { name: "Dwarven Ring",            quantity: 1, npcPrice: 2000  },
      { name: "Stone Skin Amulet",       quantity: 1, npcPrice: 5000  },
      { name: "Coal",                    quantity: 1, npcPrice: 50    },
    ],
    rewardGold: 0,
    rewardXP: 0,
    rewardItems: [],
    notes: "",
  },
  {
    id: "rashid_friday",
    npc: "Rashid",
    location: "Venore (Friday)",
    taskName: "Rashid's Daily Buy — Friday",
    items: [
      { name: "Elven Scouting Glass",    quantity: 1, npcPrice: 8000  },
      { name: "Elvish Talisman",         quantity: 1, npcPrice: 100   },
      { name: "Elven Amulet",            quantity: 1, npcPrice: 4000  },
    ],
    rewardGold: 0,
    rewardXP: 0,
    rewardItems: [],
    notes: "",
  },
  {
    id: "rashid_saturday",
    npc: "Rashid",
    location: "Ankrahmun (Saturday)",
    taskName: "Rashid's Daily Buy — Saturday",
    items: [
      { name: "Scarab Coin",             quantity: 1, npcPrice: 100   },
      { name: "Gauze Bandage",           quantity: 1, npcPrice: 100   },
      { name: "Canopic Jar",             quantity: 1, npcPrice: 500   },
    ],
    rewardGold: 0,
    rewardXP: 0,
    rewardItems: [],
    notes: "",
  },
  {
    id: "rashid_sunday",
    npc: "Rashid",
    location: "Darashia (Sunday)",
    taskName: "Rashid's Daily Buy — Sunday",
    items: [
      { name: "Mummy Trophy",            quantity: 1, npcPrice: 1000  },
      { name: "Djinn Trophy",            quantity: 1, npcPrice: 1000  },
      { name: "Pharaoh Trophy",          quantity: 1, npcPrice: 2000  },
    ],
    rewardGold: 0,
    rewardXP: 0,
    rewardItems: [],
    notes: "",
  },

  /* ─────────────────────────── GRIZZLY ADAMS ──────────────────────────── */
  {
    id: "grizzly_bog_raider",
    npc: "Grizzly Adams",
    location: "Tiquanda / Outlaw Camp",
    taskName: "Bog Raider Task",
    items: [
      { name: "Boggy Dreads",            quantity: 10, npcPrice: 320  },
    ],
    rewardGold: 0,
    rewardXP: 3000,
    rewardItems: [],
    notes: "Kill 300 Bog Raiders; collect 10 Boggy Dreads to complete.",
  },
  {
    id: "grizzly_crypt_shambler",
    npc: "Grizzly Adams",
    location: "Drefia",
    taskName: "Crypt Shambler Task",
    items: [
      { name: "Crypt Shambler Trophy",   quantity: 1,  npcPrice: 1000 },
    ],
    rewardGold: 0,
    rewardXP: 5000,
    rewardItems: [],
    notes: "Kill 300 Crypt Shamblers.",
  },
  {
    id: "grizzly_demon",
    npc: "Grizzly Adams",
    location: "Pits of Inferno / Kazordoon",
    taskName: "Demon Task",
    items: [
      { name: "Demon Trophy",            quantity: 1,  npcPrice: 5000 },
    ],
    rewardGold: 0,
    rewardXP: 20000,
    rewardItems: [
      { name: "Demon Task Points",       marketValue: 0 },
    ],
    notes: "Kill 300 Demons; high XP reward.",
  },
  {
    id: "grizzly_dragon",
    npc: "Grizzly Adams",
    location: "Various",
    taskName: "Dragon Task",
    items: [
      { name: "Dragon Trophy",           quantity: 1,  npcPrice: 2000 },
    ],
    rewardGold: 0,
    rewardXP: 10000,
    rewardItems: [],
    notes: "Kill 300 Dragons.",
  },
  {
    id: "grizzly_dragon_lord",
    npc: "Grizzly Adams",
    location: "Various",
    taskName: "Dragon Lord Task",
    items: [
      { name: "Dragon Lord Trophy",      quantity: 1,  npcPrice: 5000 },
    ],
    rewardGold: 0,
    rewardXP: 15000,
    rewardItems: [],
    notes: "Kill 300 Dragon Lords.",
  },
  {
    id: "grizzly_hydra",
    npc: "Grizzly Adams",
    location: "Tiquanda",
    taskName: "Hydra Task",
    items: [
      { name: "Hydra Trophy",            quantity: 1,  npcPrice: 5000 },
    ],
    rewardGold: 0,
    rewardXP: 10000,
    rewardItems: [],
    notes: "Kill 300 Hydras.",
  },
  {
    id: "grizzly_vampire",
    npc: "Grizzly Adams",
    location: "Drefia / Edron",
    taskName: "Vampire Task",
    items: [
      { name: "Vampire Trophy",          quantity: 1,  npcPrice: 2000 },
    ],
    rewardGold: 0,
    rewardXP: 5000,
    rewardItems: [],
    notes: "Kill 300 Vampires.",
  },
  {
    id: "grizzly_behemoth",
    npc: "Grizzly Adams",
    location: "Kha'labal / Edron",
    taskName: "Behemoth Task",
    items: [
      { name: "Behemoth Trophy",         quantity: 1,  npcPrice: 5000 },
    ],
    rewardGold: 0,
    rewardXP: 10000,
    rewardItems: [],
    notes: "Kill 300 Behemoths.",
  },
  {
    id: "grizzly_juggernaut",
    npc: "Grizzly Adams",
    location: "Farmine",
    taskName: "Juggernaut Task",
    items: [
      { name: "Juggernaut Trophy",       quantity: 1,  npcPrice: 10000 },
    ],
    rewardGold: 0,
    rewardXP: 20000,
    rewardItems: [],
    notes: "Kill 300 Juggernauts.",
  },

  /* ─────────────────────────────── YASIR ──────────────────────────────── */
  {
    id: "yasir_creature_products",
    npc: "Yasir",
    location: "Various docks (travels)",
    taskName: "Yasir — Creature Products",
    items: [
      { name: "Bat Wing",                quantity: 1,  npcPrice: 4    },
      { name: "Bear Paw",                quantity: 1,  npcPrice: 80   },
      { name: "Beholder Eye",            quantity: 1,  npcPrice: 170  },
      { name: "Black Pearl",             quantity: 1,  npcPrice: 280  },
      { name: "Bloody Pincers",          quantity: 1,  npcPrice: 250  },
      { name: "Blue Piece of Cloth",     quantity: 1,  npcPrice: 490  },
      { name: "Bone",                    quantity: 1,  npcPrice: 4    },
      { name: "Broken Halberd",          quantity: 1,  npcPrice: 50   },
      { name: "Bull Horn",               quantity: 1,  npcPrice: 300  },
      { name: "Canine Trophy",           quantity: 1,  npcPrice: 200  },
      { name: "Centipede Leg",           quantity: 1,  npcPrice: 80   },
      { name: "Cobra Tongue",            quantity: 1,  npcPrice: 100  },
      { name: "Coral",                   quantity: 1,  npcPrice: 50   },
      { name: "Crab Pincers",            quantity: 1,  npcPrice: 150  },
      { name: "Crocodile Leather",       quantity: 1,  npcPrice: 50   },
      { name: "Cyclops Toe",             quantity: 1,  npcPrice: 150  },
      { name: "Deer Trophy",             quantity: 1,  npcPrice: 100  },
      { name: "Demonic Essence",         quantity: 1,  npcPrice: 5000 },
      { name: "Devil Helmet",            quantity: 1,  npcPrice: 100  },
      { name: "Dragon Lord Feather",     quantity: 1,  npcPrice: 500  },
      { name: "Dragon Scale",            quantity: 1,  npcPrice: 200  },
      { name: "Draken Wristbands",       quantity: 1,  npcPrice: 680  },
      { name: "Elven Astral Observer",   quantity: 1,  npcPrice: 250  },
      { name: "Fairy Wings",             quantity: 1,  npcPrice: 230  },
      { name: "Fern",                    quantity: 1,  npcPrice: 60   },
      { name: "Fiery Heart",             quantity: 1,  npcPrice: 1000 },
      { name: "Focused Mind's Stone",    quantity: 1,  npcPrice: 600  },
      { name: "Garlic Necklace",         quantity: 1,  npcPrice: 100  },
      { name: "Ghoul Snack",             quantity: 1,  npcPrice: 60   },
      { name: "Giant Eye",               quantity: 1,  npcPrice: 250  },
      { name: "Giant Shrimp",            quantity: 1,  npcPrice: 300  },
      { name: "Goblin Ear",              quantity: 1,  npcPrice: 20   },
      { name: "Green Piece of Cloth",    quantity: 1,  npcPrice: 490  },
      { name: "Griffinclaw",             quantity: 1,  npcPrice: 220  },
      { name: "Hatching Horror",         quantity: 1,  npcPrice: 200  },
      { name: "Holy Orchid",             quantity: 1,  npcPrice: 250  },
      { name: "Hydra Head",              quantity: 1,  npcPrice: 250  },
      { name: "Hydra Scale",             quantity: 1,  npcPrice: 200  },
      { name: "Infernal Bolt",           quantity: 1,  npcPrice: 100  },
      { name: "Ivory Fangs",             quantity: 1,  npcPrice: 550  },
      { name: "Jellyfish Fluid",         quantity: 1,  npcPrice: 120  },
      { name: "Jungle Moss",             quantity: 1,  npcPrice: 80   },
      { name: "Lamassu Hoof",            quantity: 1,  npcPrice: 500  },
      { name: "Lizard Heart",            quantity: 1,  npcPrice: 200  },
      { name: "Lizard Leather",          quantity: 1,  npcPrice: 150  },
      { name: "Lizard Scale",            quantity: 1,  npcPrice: 150  },
      { name: "Mantassin Tail",          quantity: 1,  npcPrice: 300  },
      { name: "Marsh Stalker Beak",      quantity: 1,  npcPrice: 120  },
      { name: "Marsh Stalker Feather",   quantity: 1,  npcPrice: 80   },
      { name: "Medusa Head",             quantity: 1,  npcPrice: 300  },
      { name: "Minotaur Horn",           quantity: 1,  npcPrice: 100  },
      { name: "Minotaur Leather",        quantity: 1,  npcPrice: 60   },
      { name: "Monkey Statue",           quantity: 1,  npcPrice: 160  },
      { name: "Moohtant Talisman",       quantity: 1,  npcPrice: 450  },
      { name: "Mutated Flesh",           quantity: 1,  npcPrice: 100  },
      { name: "Mystic Turban",           quantity: 1,  npcPrice: 100  },
      { name: "Nightmare's Thorn",       quantity: 1,  npcPrice: 600  },
      { name: "Ogre Ear Stud",           quantity: 1,  npcPrice: 300  },
      { name: "Ogre Nose Ring",          quantity: 1,  npcPrice: 160  },
      { name: "Orc Tusk",                quantity: 1,  npcPrice: 60   },
      { name: "Piece of Royal Steel",    quantity: 1,  npcPrice: 500  },
      { name: "Pig Foot",                quantity: 1,  npcPrice: 60   },
      { name: "Pirate Voodoo Doll",      quantity: 1,  npcPrice: 200  },
      { name: "Pool of Chitinous Glue",  quantity: 1,  npcPrice: 100  },
      { name: "Purple Robe",             quantity: 1,  npcPrice: 100  },
      { name: "Quara Bone",              quantity: 1,  npcPrice: 160  },
      { name: "Quara Eye",               quantity: 1,  npcPrice: 200  },
      { name: "Quara Pincers",           quantity: 1,  npcPrice: 300  },
      { name: "Quara Tentacle",          quantity: 1,  npcPrice: 200  },
      { name: "Red Piece of Cloth",      quantity: 1,  npcPrice: 490  },
      { name: "Rhino Hide",              quantity: 1,  npcPrice: 180  },
      { name: "Rorc Feather",            quantity: 1,  npcPrice: 80   },
      { name: "Sabretooth",              quantity: 1,  npcPrice: 800  },
      { name: "Sandcrawler Shell",       quantity: 1,  npcPrice: 130  },
      { name: "Scale of Corruption",     quantity: 1,  npcPrice: 1000 },
      { name: "Scorpion Tail",           quantity: 1,  npcPrice: 80   },
      { name: "Sea Serpent Scale",       quantity: 1,  npcPrice: 550  },
      { name: "Seed",                    quantity: 1,  npcPrice: 20   },
      { name: "Silver Brooch",           quantity: 1,  npcPrice: 100  },
      { name: "Sliver",                  quantity: 1,  npcPrice: 400  },
      { name: "Small Tooth",             quantity: 1,  npcPrice: 4    },
      { name: "Snake Skin",              quantity: 1,  npcPrice: 20   },
      { name: "Spider Fangs",            quantity: 1,  npcPrice: 200  },
      { name: "Spitter Nose",            quantity: 1,  npcPrice: 200  },
      { name: "Srezz' Yellow Eye",       quantity: 1,  npcPrice: 600  },
      { name: "Thaian Sword",            quantity: 1,  npcPrice: 100  },
      { name: "Toad Back Wart",          quantity: 1,  npcPrice: 100  },
      { name: "Torn Shirt",              quantity: 1,  npcPrice: 20   },
      { name: "Tribal Mask",             quantity: 1,  npcPrice: 150  },
      { name: "Troll Green",             quantity: 1,  npcPrice: 40   },
      { name: "Turtle Shell",            quantity: 1,  npcPrice: 150  },
      { name: "Undertaker Tongs",        quantity: 1,  npcPrice: 180  },
      { name: "Vexclaw Talon",           quantity: 1,  npcPrice: 500  },
      { name: "Vulture Feathers",        quantity: 1,  npcPrice: 80   },
      { name: "War Crystal",             quantity: 1,  npcPrice: 100  },
      { name: "Warmaster's Wristguards", quantity: 1,  npcPrice: 700  },
      { name: "Wasp Sting",              quantity: 1,  npcPrice: 20   },
      { name: "White Piece of Cloth",    quantity: 1,  npcPrice: 490  },
      { name: "Widow's Yarn",            quantity: 1,  npcPrice: 150  },
      { name: "Wild Flowers",            quantity: 1,  npcPrice: 60   },
      { name: "Wyvern Talisman",         quantity: 1,  npcPrice: 400  },
      { name: "Yellow Piece of Cloth",   quantity: 1,  npcPrice: 490  },
    ],
    rewardGold: 0,
    rewardXP: 0,
    rewardItems: [],
    notes: "Yasir buys creature products that most other NPCs don't buy.",
  },
];
